# -*- coding: utf-8 -*-
"""TP_AYMEN (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjV5_GrgViizLkBxUE-hFPMeI7KMWUyd
"""

!pip install osmnx

import ee
import geemap
import osmnx as ox
import geopandas as gpd

ee.Authenticate()
ee.Initialize(project='ee-aymenfarsi2000')

place_name = "Lebel-sur-Quévillon, Quebec, Canada"
gdf = ox.geocode_to_gdf(place_name)
geo_json = gdf.__geo_interface__
region = ee.FeatureCollection(geo_json)
bbox = gdf.total_bounds

print(bbox)

avant_date_firms = '2023-05-31'
apres_date_firms = '2023-06-02'


firms_data = ee.ImageCollection('FIRMS').filterDate(avant_date_firms, apres_date_firms).filterBounds(region.geometry())
wildfire2023 = ee.Image("projects/sat-io/open-datasets/CA_FOREST/CA_Forest_Wildfire_2023_Summer_Fall");

firms_vis_params = {
    'min': 300,
    'max': 400,
    'palette': ['yellow', 'orange', 'red']
}

"""These visualization parameters define how the fire points will be displayed on the map:
*   **min**: The minimum brightness value to map to the first color in the palette.
*   **max**: The maximum brightness value to map to the last color in the palette.
*   **palette**: A list of colors used to represent the range of brightness values, from low (yellow) to high (red).

"""

Apres_date_landsat1 = '2023-06-21'
Apres_date_landsat2 = '2023-08-30'

landsat_image = ee.ImageCollection('LANDSAT/LC09/C02/T1_L2').filterDate(Apres_date_landsat1, Apres_date_landsat2).filterBounds(region.geometry()).sort('CLOUD_COVER').first()
def applyScaleFactors(image):
    optical = image.select('SR_B.*') \
                   .multiply(0.0000275) \
                   .add(-0.2)

    thermal = image.select('ST_B.*') \
                   .multiply(0.00341802) \
                   .add(149.0)

    return (image
            .addBands(optical, overwrite=True)
            .addBands(thermal, overwrite=True))

img = applyScaleFactors(landsat_image)
Vrai_Couleur=img.select(['SR_B4', 'SR_B3', 'SR_B2'])
Fausse_couleur=img.select(['SR_B5', 'SR_B4', 'SR_B3'])

nbr = landsat_image.expression(
    '(NIR - SWIR2) / (NIR + SWIR2)',
    {
        'NIR': landsat_image.select('SR_B5'),
        'SWIR2': landsat_image.select('SR_B7')
    }
).rename('NBR')

nbr_vis = {'min': -1, 'max': 1, 'palette': ['white','yellow','orange','red','darkred']}

Map = geemap.Map()
Map.centerObject(region, 10)
Map.add_basemap("SATELLITE")
# Map.addLayer(nbr.select('NBR'), nbr_vis, 'Landsat NBR')
Map.addLayer(Vrai_Couleur, {'min':0, 'max':0.5}, 'Vrai_couleur')
Map.addLayer(Fausse_couleur, {'min':0, 'max':0.5}, 'Fausse_couleur')
Map.addLayer(firms_data.mosaic().select('T21'), firms_vis_params, 'FIRMS')
Map.addLayer(wildfire2023, {'color': 'red'}, 'Wildfire2023')

Map.addLayer(region, {'color': 'red'}, 'Lebel-sur-Quévillon')
Map.add_draw_control()
Map